# Generated by Django 4.2.7 on 2024-01-24 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='webapp.customer')),
                ('inverters_ordered', models.ManyToManyField(related_name='orders', to='webapp.solarinverter')),
                ('panels_ordered', models.ManyToManyField(related_name='orders', to='webapp.solarpanel')),
            ],
        ),
        migrations.DeleteModel(
            name='SolarInstallation',
        ),
    ]
